name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: if [ -f Dockerfile ]; then docker build . --file Dockerfile --tag practical-nlp:$(date +%s); fi
